### ISSUE TITLE
General documentation updates

### ISSUE THREAD

**Issue by akeeste** [MHKiT-Software/MHKiT#59]
Priorities before OREC:
- [x] Update all links #60
- [x] Ensure installation instructions are very clear for both Python and MATLAB #58 
- [x] Ensure compatible Python versions (3.8-3.11) and dependencies are clear #60
